### PR TITLE
Add thumbnail

### PR DESCRIPTION
**Pull request by jjc2718**
As requested in: https://github.com/manubot/catalog/pull/56#discussion_r741979281

### CODE REVIEW

**Review by cgreene — APPROVED** [review]

**Comment by ben-heil** [comment]
LGTM, is there a way to preview the manubot build to make sure the thumbnail works like you want?

**Review by ben-heil — APPROVED** [review]

**Comment by jjc2718** [comment]
Just realized Manubot has some [guidelines for making a thumbnail](https://github.com/manubot/catalog#thumbnail-guidelines) - I'll update mine this afternoon and edit the PR.

> LGTM, is there a way to preview the manubot build to make sure the thumbnail works like you want?

Good question, I'm not sure. Maybe @vincerubinetti would know?

**Comment by vincerubinetti** [comment]
I believe the thumbnail is only used for the catalog. I don't think we ever hooked it up to anything else, like using it for the favicon. That is, it won't appear anywhere in your manuscript. 

If you want to see how it looks in the catalog, here's a very crude preview:

image

**Comment by vincerubinetti** [comment]
Looked through your manuscript and here's my suggestion for a thumbnail (though ideally higher res from svg/powerpoint source).

image

**Pull request merged**
